### PR TITLE
Add initial argument_spec to automagically validate all vars

### PR DESCRIPTION
**Pull request by karras**
## Description

This PR adds the so-called `argument_spec` which is somewhat new since ~2.12 and nicely validates if all required variables are provided and second if they are valid.

## Dependencies

n/a

### CODE REVIEW

**Comment by karras** [comment]
I can easily rebase the PR once #1 has been merged which also resolves the broken lint step.

**Comment by karras** [comment]
Rebased onto `main`

**Comment by karras** [comment]
```
$ ansible-doc --type role -r . main ansible-role-potos_wallpaper
> ANSIBLE-ROLE-POTOS_WALLPAPER    ([...])

ENTRY POINT: main - Role to manage wallpapers of Potos Linux Clients.

OPTIONS (= is mandatory):

- potos_wallpaper_default_name
        Name of the default wallpaper file.
        [Default: warty-final-ubuntu.png]
        type: str

- potos_wallpaper_images
        List of files to be found under 'potos_wallpaper' to be added as background, first element is set as default.
        [Default: []]
        elements: str
        type: list

```

**Comment by fadnincx** [comment]
@karras should `potos_wallpaper_default_name` really be in this list? It's defined per operating system and then included with precedence 18 of 22 (according to the specification)[https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#understanding-variable-precedence]. So the user basically has no direct way to overwrite this variable.

**Comment by karras** [comment]
Yes, `vars` are harder to overwrite though it is still possible and I think it still makes sense to verify the validity of the input. What if you define a wrong value in `vars` as part of the role development?

**Pull request merged**
